name = "crescentrose-web"
compatibility_date = "2025-06-09"
routes = [
  { pattern = "crescentro.se", custom_domain = true },
  { pattern = "www.crescentro.se", custom_domain = true },
]


[assets]
directory = "./public"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"
